# Generated by Django 5.2.1 on 2025-05-07 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('age', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)], verbose_name='Возраст')),
                ('sex', models.CharField(choices=[('m', 'Мужчина'), ('f', 'Женщина')], max_length=10, verbose_name='Пол')),
                ('active', models.BooleanField(verbose_name='Активный')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['surname'],
                'indexes': [models.Index(fields=['surname'], name='app1_studen_surname_62ad59_idx')],
                'unique_together': {('name', 'surname')},
            },
        ),
    ]
